#!/usr/bin/env bash
# Lab 27 setup — build the "before" state for CPU steal time.
#
# IMPORTANT (read this before you run it): genuine %st requires a real
# hypervisor actively denying your VM's vCPUs time, because a noisy
# neighbor on the same host is hogging physical cores. We can't manufacture
# that reliably from inside a single lab VM. This script does two things
# instead, and keeps them clearly separate:
#
#   1. A LIVE, REAL exercise: it runs stress-ng inside YOUR VM and records
#      real vmstat/mpstat output. This will show high %us/%sy (the guest's
#      own CPU use), NOT %st — because this load is self-inflicted, not
#      stolen. This is the control/contrast case: what high CPU looks like
#      when it's your own workload's fault.
#   2. Reference sample files: pre-written, labeled-as-such text captures
#      of what real %st looks like in vmstat/mpstat output, based on a
#      genuine noisy-neighbor incident pattern. These are NOT generated by
#      running anything on your machine — they're illustrative data files
#      to practice reading and diagnosing, same as being handed a paste of
#      output in a ticket.
set -euo pipefail

WORKDIR="/var/tmp/lab27"
mkdir -p "$WORKDIR"

echo "[setup] checking for stress-ng and sysstat (mpstat)..."
if ! command -v stress-ng >/dev/null 2>&1 || ! command -v mpstat >/dev/null 2>&1; then
  echo "[setup] installing stress-ng and sysstat via apt..."
  sudo apt-get update -qq
  sudo apt-get install -y -qq stress-ng sysstat
fi

echo "[setup] detecting virtualization type (context for the lab)..."
if command -v systemd-detect-virt >/dev/null 2>&1; then
  systemd-detect-virt || true
else
  echo "systemd-detect-virt not available — skip"
fi

NCPU=$(nproc)
echo "[setup] this VM has $NCPU vCPU(s)"

echo "[setup] running a REAL self-inflicted CPU load for 20s (stress-ng)"
echo "[setup] capturing vmstat + mpstat output while it runs..."

stress-ng --cpu "$NCPU" --cpu-method matrixprod --timeout 20s &
STRESS_PID=$!

vmstat 1 20 > "$WORKDIR/vmstat-selfload.log" &
VMSTAT_PID=$!
mpstat -P ALL 1 20 > "$WORKDIR/mpstat-selfload.log" &
MPSTAT_PID=$!

wait "$STRESS_PID" 2>/dev/null || true
wait "$VMSTAT_PID" 2>/dev/null || true
wait "$MPSTAT_PID" 2>/dev/null || true

echo "[setup] real capture written to:"
echo "    $WORKDIR/vmstat-selfload.log"
echo "    $WORKDIR/mpstat-selfload.log"

echo "[setup] writing labeled REFERENCE samples (not live data — see README)..."

cat > "$WORKDIR/vmstat-steal-REFERENCE.log" <<'EOF'
# REFERENCE SAMPLE — illustrative, captured pattern from a real noisy-neighbor
# incident on shared cloud infra. NOT generated on this machine.
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 4  0      0 812340  98120 612044    0    0     0     3  620  980  8  3 44  0 45
 5  0      0 809212  98120 612044    0    0     0     0  598  944  6  4 42  0 48
 3  0      0 807880  98120 612044    0    0     0     2  611  967  7  3 41  0 49
 6  0      0 805102  98120 612044    0    0     0     0  634  991  9  4 40  0 47
 4  0      0 804488  98120 612044    0    0     0     4  601  955  7  3 43  0 47
EOF

cat > "$WORKDIR/mpstat-steal-REFERENCE.log" <<'EOF'
# REFERENCE SAMPLE — illustrative, captured pattern from a real noisy-neighbor
# incident on shared cloud infra. NOT generated on this machine.
Linux 5.15.0-generic (web-03)   08/01/26        _x86_64_        (4 CPU)

12:00:01     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
12:00:02     all    7.21    0.00    3.05    0.10    0.00    0.20   46.30    0.00    0.00   43.14
12:00:02       0    7.00    0.00    3.00    0.00    0.00    0.00   62.00    0.00    0.00   28.00
12:00:02       1    6.90    0.00    3.10    0.20    0.00    0.30   58.40    0.00    0.00   31.10
12:00:02       2    8.10    0.00    3.20    0.10    0.00    0.10   28.50    0.00    0.00   60.00
12:00:02       3    6.84    0.00    2.90    0.00    0.00    0.30   36.20    0.00    0.00   53.76
EOF

echo "[setup] reference samples written to:"
echo "    $WORKDIR/vmstat-steal-REFERENCE.log"
echo "    $WORKDIR/mpstat-steal-REFERENCE.log"
echo "[setup] done."
